# Generated by Django 5.0.6 on 2024-07-23 00:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AFSCTable',
            fields=[
                ('PK_AFSC', models.BigIntegerField(primary_key=True, serialize=False)),
                ('AFSCTitle', models.CharField(max_length=100)),
                ('AFSCDescription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesTable',
            fields=[
                ('PK_Course', models.BigIntegerField(primary_key=True, serialize=False)),
                ('CourseTitle', models.CharField(max_length=200)),
                ('CourseDescription', models.CharField(max_length=200)),
                ('RelatedCourse', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RANK', models.CharField(max_length=200)),
                ('LAST_NAME', models.CharField(max_length=200)),
                ('FIRST_NAME', models.CharField(max_length=200)),
                ('MIDDLE_NAME', models.CharField(blank=True, max_length=200, null=True)),
                ('EXTENSION_NAME', models.CharField(blank=True, max_length=200, null=True)),
                ('AFPSN', models.CharField(max_length=200)),
                ('BOS', models.CharField(max_length=200)),
                ('SEX', models.CharField(max_length=10)),
                ('BIRTHDAY', models.DateField(blank=True, null=True)),
                ('CONTACT_NUMBER', models.CharField(blank=True, max_length=200, null=True)),
                ('ADDRESS', models.CharField(blank=True, max_length=200, null=True)),
                ('CLASSIFICATION', models.CharField(max_length=200)),
                ('CATEGORY', models.CharField(max_length=200)),
                ('SOURCE_OF_ENLISTMENT_COMMISION', models.CharField(max_length=200)),
                ('PILOT_RATED_NON_RATED', models.CharField(blank=True, max_length=200, null=True)),
                ('AFSC', models.CharField(blank=True, max_length=200, null=True)),
                ('HIGHEST_PME_COURSES', models.CharField(blank=True, max_length=200, null=True)),
                ('EFFECTIVE_DATE_APPOINTMENT', models.DateField()),
                ('EFFECTIVE_DATE_ENTERED', models.DateField()),
                ('DATE_LAST_PROMOTION_APPOINTMENT', models.DateField(blank=True, null=True)),
                ('UNIT', models.CharField(blank=True, max_length=200, null=True)),
                ('SUB_UNIT', models.CharField(blank=True, max_length=200, null=True)),
                ('DATE_LASTFULL_REENLISTMENT', models.DateField(blank=True, null=True)),
                ('DATE_LAST_ETAD', models.DateField(blank=True, null=True)),
                ('INACTIVITY_REASON', models.CharField(blank=True, max_length=200, null=True)),
                ('IS_ACTIVE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelTable',
            fields=[
                ('PK_Personnel', models.BigIntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('MiddleName', models.CharField(blank=True, max_length=200, null=True)),
                ('NameSuffix', models.CharField(blank=True, max_length=200, null=True)),
                ('BOS', models.CharField(max_length=200)),
                ('Sex', models.CharField(max_length=10)),
                ('Birthday', models.DateField(blank=True, null=True)),
                ('ContactNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('SerialNumber', models.CharField(max_length=200)),
                ('Rank', models.CharField(max_length=200)),
                ('DateEnlisted', models.DateField(blank=True, null=True)),
                ('DatePromoted', models.DateField(blank=True, null=True)),
                ('TypeOfPersonnel', models.DateField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AFPSN', models.CharField(max_length=200)),
                ('RANK', models.CharField(max_length=200)),
                ('LAST_NAME', models.CharField(max_length=200)),
                ('FIRST_NAME', models.CharField(max_length=200)),
                ('MIDDLE_NAME', models.CharField(max_length=200)),
                ('SUFFIX', models.CharField(max_length=200)),
                ('MOTHER_UNIT', models.CharField(max_length=200)),
                ('NEW_UNIT', models.CharField(max_length=200)),
                ('SUB_UNIT', models.CharField(blank=True, max_length=200, null=True)),
                ('REASSIGN_EFFECTIVEDDATE', models.DateField()),
                ('ASSIGNMENT_CATEGORY', models.CharField(max_length=200)),
                ('DURATION', models.CharField(blank=True, max_length=200, null=True)),
                ('REASSIGN_EFFECTIVEDDATE_UNTIL', models.DateField(blank=True, null=True)),
                ('IS_ARCHIVED', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'placementinfo',
            },
        ),
        migrations.CreateModel(
            name='PositionTypeTable',
            fields=[
                ('PK_PositionType', models.BigIntegerField(primary_key=True, serialize=False)),
                ('TypeTitle', models.CharField(max_length=100)),
                ('TypeDescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AFSCRelatedCourse',
            fields=[
                ('PK_AFSCRelatedCourse', models.BigIntegerField(primary_key=True, serialize=False)),
                ('UnitName', models.CharField(max_length=100)),
                ('UnitDescription', models.CharField(max_length=200)),
                ('Logo', models.CharField(max_length=100)),
                ('FK_MotherUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.afscrelatedcourse')),
            ],
        ),
        migrations.CreateModel(
            name='AFSCCourseTable',
            fields=[
                ('PK_AFSCCourse', models.BigIntegerField(primary_key=True, serialize=False)),
                ('RelatedCourse', models.CharField(max_length=100)),
                ('FK_AFSC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.afsctable')),
                ('FK_Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.coursestable')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelHistoryTable',
            fields=[
                ('PK_Personnel', models.BigIntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(blank=True, max_length=100)),
                ('NameSuffix', models.CharField(blank=True, max_length=50)),
                ('BOS', models.CharField(max_length=100)),
                ('Sex', models.CharField(max_length=10)),
                ('Birthday', models.DateField(blank=True)),
                ('ContactNumber', models.CharField(blank=True, max_length=200)),
                ('Address', models.CharField(blank=True, max_length=200)),
                ('SerialNumber', models.CharField(max_length=200)),
                ('Rank', models.CharField(max_length=200)),
                ('DateEnlisted', models.DateField(blank=True)),
                ('DatePromoted', models.DateField(blank=True, null=True)),
                ('TypeOfPersonnel', models.DateField(blank=True)),
                ('DateEdited', models.DateField(default=datetime.date.today)),
                ('FK_Personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.personneltable')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelFilesTable',
            fields=[
                ('PK_PersonnelFiles', models.BigIntegerField(primary_key=True, serialize=False)),
                ('DateUploaded', models.DateField(default=datetime.date.today)),
                ('FileName', models.CharField(max_length=200)),
                ('FileType', models.CharField(max_length=200)),
                ('FileLocation', models.CharField(max_length=200)),
                ('FK_Personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.personneltable')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='myapp.placement')),
            ],
        ),
        migrations.CreateModel(
            name='UnitsTable',
            fields=[
                ('PK_Units', models.BigIntegerField(primary_key=True, serialize=False)),
                ('UnitName', models.CharField(max_length=100)),
                ('UnitDescription', models.CharField(max_length=200)),
                ('Logo', models.CharField(max_length=200)),
                ('FK_MotherUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unitstable')),
            ],
        ),
        migrations.CreateModel(
            name='PositionSuggestedAFSC',
            fields=[
                ('PK_UnitWorkPosition', models.BigIntegerField(primary_key=True, serialize=False)),
                ('PositionTitle', models.CharField(max_length=100)),
                ('PositionDescription', models.CharField(max_length=100)),
                ('FK_PositionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.positiontypetable')),
                ('FK_Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unitstable')),
            ],
        ),
        migrations.CreateModel(
            name='UnitWorkPositionTable',
            fields=[
                ('PK_UnitWorkPosition', models.BigIntegerField(primary_key=True, serialize=False)),
                ('PositionTitle', models.CharField(max_length=100)),
                ('PositionDescription', models.CharField(max_length=100)),
                ('FK_PositionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.positiontypetable')),
                ('FK_Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unitstable')),
            ],
        ),
    ]
