# Generated by Django 5.0.6 on 2024-07-29 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RANK', models.CharField(max_length=200)),
                ('LAST_NAME', models.CharField(max_length=200)),
                ('FIRST_NAME', models.CharField(max_length=200)),
                ('MIDDLE_NAME', models.CharField(blank=True, max_length=200, null=True)),
                ('EXTENSION_NAME', models.CharField(blank=True, max_length=200, null=True)),
                ('SERIAL_NUMBER', models.CharField(max_length=200)),
                ('BOS', models.CharField(max_length=200)),
                ('SEX', models.CharField(max_length=10)),
                ('BIRTHDAY', models.DateField(blank=True, null=True)),
                ('CONTACT_NUMBER', models.CharField(blank=True, max_length=200, null=True)),
                ('ADDRESS', models.CharField(blank=True, max_length=200, null=True)),
                ('CLASSIFICATION', models.CharField(max_length=200)),
                ('CATEGORY', models.CharField(max_length=200)),
                ('SOURCE_OF_ENLISTMENT_COMMISION', models.CharField(max_length=200)),
                ('PILOT_RATED_NON_RATED', models.CharField(blank=True, max_length=200, null=True)),
                ('AFSC', models.CharField(blank=True, max_length=200, null=True)),
                ('HIGHEST_PME_COURSES', models.CharField(blank=True, max_length=200, null=True)),
                ('EFFECTIVE_DATE_APPOINTMENT', models.DateField()),
                ('EFFECTIVE_DATE_ENTERED', models.DateField()),
                ('DATE_LAST_PROMOTION_APPOINTMENT', models.DateField(blank=True, null=True)),
                ('UNIT', models.CharField(blank=True, max_length=200, null=True)),
                ('SUB_UNIT', models.CharField(blank=True, max_length=200, null=True)),
                ('DATE_LASTFULL_REENLISTMENT', models.DateField(blank=True, null=True)),
                ('DATE_LAST_ETAD', models.DateField(blank=True, null=True)),
                ('INACTIVITY_REASON', models.CharField(blank=True, max_length=200, null=True)),
                ('IS_ACTIVE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AFPSN', models.CharField(max_length=200)),
                ('RANK', models.CharField(max_length=200)),
                ('LAST_NAME', models.CharField(max_length=200)),
                ('FIRST_NAME', models.CharField(max_length=200)),
                ('MIDDLE_NAME', models.CharField(max_length=200)),
                ('SUFFIX', models.CharField(max_length=200)),
                ('MOTHER_UNIT', models.CharField(max_length=200)),
                ('NEW_UNIT', models.CharField(max_length=200)),
                ('SUB_UNIT', models.CharField(blank=True, max_length=200, null=True)),
                ('REASSIGN_EFFECTIVEDDATE', models.DateField()),
                ('ASSIGNMENT_CATEGORY', models.CharField(max_length=200)),
                ('DURATION', models.CharField(blank=True, max_length=200, null=True)),
                ('REASSIGN_EFFECTIVEDDATE_UNTIL', models.DateField(blank=True, null=True)),
                ('ORDER_UPLOADFILE', models.FileField(upload_to='orders/')),
                ('IS_ARCHIVED', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'placementinfo',
            },
        ),
        migrations.CreateModel(
            name='PersonnelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='personnel_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='myapp.personnelitem')),
            ],
        ),
        migrations.CreateModel(
            name='UnitsTable',
            fields=[
                ('PK_Units', models.BigAutoField(primary_key=True, serialize=False)),
                ('UnitName', models.CharField(max_length=100)),
                ('UnitDescription', models.CharField(max_length=200)),
                ('UnitCategory', models.CharField(max_length=200)),
                ('Logo', models.CharField(blank=True, max_length=200, null=True)),
                ('FK_MotherUnit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.unitstable')),
            ],
        ),
    ]
