# Generated by Django 5.0.6 on 2024-06-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='ORDER_UPLOADFILE',
            field=models.FileField(upload_to='media/'),
        ),
    ]
