# Generated by Django 5.0.6 on 2024-05-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_FULLNAME', models.CharField(max_length=200)),
                ('_PresentUNIT', models.CharField(max_length=200)),
                ('_subUNIT', models.CharField(max_length=200)),
                ('_reassignedDATE', models.CharField(max_length=200)),
                ('_dateORDER', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='personnel_item',
            old_name='AFSN',
            new_name='_AFSN',
        ),
    ]
