# Generated by Django 5.0.6 on 2024-07-29 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitsTable',
            fields=[
                ('PK_Units', models.BigAutoField(primary_key=True, serialize=False)),
                ('UnitName', models.CharField(max_length=100)),
                ('UnitDescription', models.CharField(max_length=200)),
                ('UnitCategory', models.CharField(max_length=200)),
                ('Logo', models.CharField(blank=True, max_length=200, null=True)),
                ('FK_MotherUnit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.unitstable')),
            ],
        ),
    ]
