# Generated by Django 5.0.6 on 2024-06-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='PresentUNIT',
            new_name='AFPSN',
        ),
        migrations.RenameField(
            model_name='placement',
            old_name='dateORDER',
            new_name='ORDERUPLOAD',
        ),
        migrations.RenameField(
            model_name='placement',
            old_name='reassignedDATE',
            new_name='PRESENTUNIT',
        ),
        migrations.RenameField(
            model_name='placement',
            old_name='subUNIT',
            new_name='REASSIGNEDDATE',
        ),
    ]
