# Generated by Django 5.0.6 on 2024-06-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Placement',
        ),
    ]
