# Generated by Django 5.0.6 on 2024-05-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_placement_rename_afsn_personnel_item__afsn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel_item',
            old_name='_AFSN',
            new_name='AFSN',
        ),
        migrations.RenameField(
            model_name='personnel_item',
            old_name='_FULLNAME',
            new_name='FULLNAME',
        ),
        migrations.RenameField(
            model_name='personnel_item',
            old_name='_RANK',
            new_name='RANK',
        ),
        migrations.RenameField(
            model_name='personnel_item',
            old_name='_UNIT',
            new_name='UNIT',
        ),
        migrations.RenameField(
            model_name='placement',
            old_name='_FULLNAME',
            new_name='FULLNAME',
        ),
        migrations.RenameField(
            model_name='placement',
            old_name='_PresentUNIT',
            new_name='PresentUNIT',
        ),
        migrations.RenameField(
            model_name='placement',
            old_name='_dateORDER',
            new_name='dateORDER',
        ),
        migrations.RenameField(
            model_name='placement',
            old_name='_reassignedDATE',
            new_name='reassignedDATE',
        ),
        migrations.RenameField(
            model_name='placement',
            old_name='_subUNIT',
            new_name='subUNIT',
        ),
    ]
