# Generated by Django 5.0.6 on 2024-06-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_placement_order_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='IS_ARCHIVED',
            field=models.BooleanField(default=False),
        ),
    ]
