# Generated by Django 5.0.6 on 2024-05-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename__afsn_personnel_item_afsn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel_item',
            old_name='FULLNAME',
            new_name='ADDRESS',
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='AFSC',
            field=models.IntegerField(default=987665445),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='BOS',
            field=models.CharField(default=123321, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='CONTACT_NUMBER',
            field=models.IntegerField(default=97676276272),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='DATE_OFAPPOINTMENT',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='DATE_OFLASTPROMOTION',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='EFFECTIVE_DATEENTERED',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='EXTENSION_NAME',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='FIRSTNAME',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='FIRST_TRANCH',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='LASTNAME',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='LENGTHSERVICE',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='MIDDLENAME',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='PILOT_RATED_NOT',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='PME_COURSES',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='REGULAR_RESERVE',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='SECOND_TRANCH',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='SERIAL_NUMBER',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='SEX',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='SUB_UNIT',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel_item',
            name='AFSN',
            field=models.IntegerField(),
        ),
    ]
