# Generated by Django 5.0.6 on 2024-05-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_fullname_personnel_item_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel_item',
            name='DATE_ENTERED',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel_item',
            name='NR',
            field=models.CharField(default=21231, max_length=200),
            preserve_default=False,
        ),
    ]
