# Generated by Django 5.0.6 on 2024-05-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_personnel_item_afsc_alter_personnel_item_afsn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NR', models.CharField(max_length=200)),
                ('RANK', models.CharField(max_length=200)),
                ('LAST_NAME', models.CharField(max_length=200)),
                ('FIRST_NAME', models.CharField(max_length=200)),
                ('MIDDLE_NAME', models.CharField(max_length=200)),
                ('EXTENSION_NAME', models.CharField(blank=True, max_length=200, null=True)),
                ('SERIAL_NUMBER', models.CharField(max_length=200)),
                ('BOS', models.CharField(max_length=200)),
                ('SEX', models.CharField(max_length=10)),
                ('BIRTHDAY', models.DateField()),
                ('CONTACT_NUMBER', models.CharField(max_length=200)),
                ('ADDRESS', models.CharField(max_length=200)),
                ('REGULAR_RESERVE', models.CharField(max_length=200)),
                ('PILOT_RATED_NON_RATED', models.CharField(max_length=200)),
                ('AFSC', models.CharField(max_length=200)),
                ('HIGHEST_PME_COURSES', models.CharField(max_length=200)),
                ('EFFECTIVE_DATE_APPOINTMENT', models.DateField()),
                ('EFFECTIVE_DATE_ENTERED', models.DateField()),
                ('LENGTH_OF_SERVICE', models.CharField(max_length=200)),
                ('DATE_LAST_PROMOTION_APPOINTMENT', models.DateField()),
                ('UNIT', models.CharField(max_length=200)),
                ('SUB_UNIT', models.CharField(max_length=200)),
                ('DATE_LAST_1ST_TRANCH_REENLISTMENT', models.DateField()),
                ('DATE_LAST_2ND_TRANCH_REENLISTMENT', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Personnel_Item',
        ),
    ]
