# Generated by Django 5.0.6 on 2024-05-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_personnelitem_delete_personnel_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelitem',
            name='AFSC',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personnelitem',
            name='CONTACT_NUMBER',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personnelitem',
            name='DATE_LAST_1ST_TRANCH_REENLISTMENT',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personnelitem',
            name='DATE_LAST_2ND_TRANCH_REENLISTMENT',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personnelitem',
            name='DATE_LAST_PROMOTION_APPOINTMENT',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personnelitem',
            name='PILOT_RATED_NON_RATED',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personnelitem',
            name='REGULAR_RESERVE',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personnelitem',
            name='SUB_UNIT',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
