# Generated by Django 5.0.6 on 2024-05-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_personnelitem_afsc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelitem',
            name='HIGHEST_PME_COURSES',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
