# Generated by Django 5.0.6 on 2024-05-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_personnelitem_highest_pme_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelitem',
            name='AFSN',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
