# Generated by Django 5.0.6 on 2024-05-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_personnelitem_nr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnelitem',
            old_name='AFSN',
            new_name='NR',
        ),
    ]
