# Generated by Django 5.0.6 on 2024-05-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_personnelitem_afsn'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchPersonnelmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('afsn', models.CharField(max_length=10, unique=True)),
                ('rank', models.CharField(max_length=10)),
                ('classification', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=6)),
                ('unit', models.CharField(max_length=100)),
            ],
        ),
    ]
