# Generated by Django 5.0.6 on 2024-05-21 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_searchpersonnelmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='searchPersonnelmodel',
        ),
    ]
