# Generated by Django 5.0.6 on 2024-05-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_personnel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
