# Generated by Django 5.0.6 on 2024-05-29 05:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delete_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelitem',
            name='LENGTH_OF_SERVICE',
        ),
        migrations.RemoveField(
            model_name='personnelitem',
            name='REGULAR_RESERVE',
        ),
        migrations.AddField(
            model_name='personnelitem',
            name='CATEGORY',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnelitem',
            name='CLASSIFICATION',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnelitem',
            name='SOURCE_OF_ENLISTMENT',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
