# Generated by Django 5.0.6 on 2024-05-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_personnelitem_length_of_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnelitem',
            old_name='DATE_LAST_1ST_TRANCH_REENLISTMENT',
            new_name='DATE_1ST_TRANCH_REENLISTMENT',
        ),
        migrations.RenameField(
            model_name='personnelitem',
            old_name='DATE_LAST_2ND_TRANCH_REENLISTMENT',
            new_name='DATE_2ND_TRANCH_REENLISTMENT',
        ),
        migrations.RenameField(
            model_name='personnelitem',
            old_name='SOURCE_OF_ENLISTMENT',
            new_name='SOURCE_OF_ENLISTMENT_COMMISION',
        ),
        migrations.RemoveField(
            model_name='personnelitem',
            name='NR',
        ),
        migrations.AlterField(
            model_name='personnelitem',
            name='ADDRESS',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personnelitem',
            name='UNIT',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
