# Generated by Django 5.0.6 on 2024-05-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_date_last_1st_tranch_reenlistment_personnelitem_date_1st_tranch_reenlistment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelitem',
            name='DATE_1ST_TRANCH_REENLISTMENT',
        ),
        migrations.RemoveField(
            model_name='personnelitem',
            name='DATE_2ND_TRANCH_REENLISTMENT',
        ),
        migrations.AddField(
            model_name='personnelitem',
            name='DATE_FIRST_TRANCHE_REENLISTMENT',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnelitem',
            name='DATE_SECOND_TRANCHE_REENLISTMENT',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personnelitem',
            name='BIRTHDAY',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personnelitem',
            name='DATE_LAST_PROMOTION_APPOINTMENT',
            field=models.DateField(blank=True, null=True),
        ),
    ]
